### ISSUE TITLE
Travis build fails: "Read-only file system"

### ISSUE THREAD

**Issue by rschmitt** [japaric/trust#46]
[Heatseeker](https://github.com/rschmitt/heatseeker) has a [build script](https://github.com/rschmitt/heatseeker/blob/master/build.rs) that collects some build-time metadata and writes a version.rs file. After migrating to trust, Travis builds (except for builds targeting Darwin) are [failing](https://travis-ci.org/rschmitt/heatseeker/builds/190164218) with the following error:

```
error: failed to run custom build command for `heatseeker v1.5.0 (file:///project)`
process didn't exit successfully: `/target/debug/build/heatseeker-77dc6031b5733332/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 30, message: "Read-only file system" } }', ../src/libcore/result.rs:837
```

The custom build command never caused any problems before, and somehow it's still not causing problems for Darwin builds. I'm not sure if the problem is in the trust template, my adaptation of it, or Travis itself.

**Comment by japaric** [comment]
This is because `cross`, which uses Docker under the hood (only for Linux), mounts the Cargo project as [read only](https://github.com/japaric/cross#caveats--gotchas). That's why the build script fails.

Build scripts shouldn't modify the `src` directory as that can mess up Cargo "freshness" check which in turn can cause consecutive `cargo build`s to always rebuild the crate.

The "proper" way to pass version information is to [write to a file](https://github.com/rust-lang-nursery/rustup.rs/blob/438129108d66149a2fa9ee3e30028bf528a1b906/build.rs#L21) in the target directory (`OUT_DIR`) and then [`include_str` that](https://github.com/rust-lang-nursery/rustup.rs/blob/438129108d66149a2fa9ee3e30028bf528a1b906/src/rustup-cli/common.rs#L344) into your source.

**Comment by rschmitt** [comment]
Thanks, this saved me a lot of time. I noticed that `git rev-parse` no longer runs on the Linux builds; I assume this means that cross's Docker images don't include git?

**Comment by japaric** [comment]
> this means that cross's Docker images don't include git?

They don't. I think they should, to support this pattern.

**Comment by maccoda** [comment]
I am getting the same error but mine is due to the integration test I am running which produces a file as the output. I have tried writing outside of the source directory using `../out` and for this I do not have permission, then writing into `target` as the build does still returned `Read-only file system`. So I was just wondering is there a way to actually test this in the Docker image or will I just not be able to run these tests on this CI?

**Comment by japaric** [comment]
> ... which produces a file as the output.

You should be writing this file to a temporary directory with delete-on-drop semantics. That's the standard-ish practice. Check the [tempdir](https://doc.rust-lang.org/tempdir/tempdir/index.html) crate.

**Comment by maccoda** [comment]
Thanks for that. Will give that a go.

**Comment by hoodie** [comment]
hey, do we want to add git to the Dockerfiles? I kinda already did the work https://github.com/hoodie/cross/commit/a6eed716e5689e5ede46133a35e8c1c7e2f495d4
