### ISSUE TITLE
Potential xz / gzip breakage

### ISSUE THREAD

**Issue by CryZe** [japaric/trust#78]
The latest nightly doesn't work with trust anymore. It could be related to the switch to xz, but it could also be something else. Here's the failed build: https://travis-ci.org/CryZe/livesplit-core/jobs/241630754#L298

**Comment by dzamlo** [comment]
The problem is that the the binary version of cross was available for `x86_64-unknown-linux-gnu` and a old version version of `ci/install.sh` used that. For the latest version of cross, this version not available.

The fact that your build failed only for nightly seems to be because cross was updated just between the the build for the nightly version and the previous build (build 147.34 used v0.1.10, build 147.36 used v0.1.11).

To resolve his issue, you must update the `ci/install.sh` script.

But there is another issue, the docker image for `japaric/x86_64-unknown-linux-gnu:v0.1.11` is not (yet?) available. This means that build with `TARGET=x86_64-unknown-linux-gnu` still fails at the moment.

**Comment by CryZe** [comment]
Nice everything works now :)

**Comment by japaric** [comment]
Sorry for the breakage :-(.
